##        General Configuration
# auto_save : On every changes of shape, save changes on json file
# store_data : saving image raw binary data in json file. Recommended to set false.
##

auto_save: false
display_label_popup: true
store_data: false
keep_prev: false
keep_prev_scale: false
keep_prev_brightness: false
keep_prev_contrast: false
logger_level: info

##        Label Configuration
#  flags: classes of image file is declared as a list. Each flag can have true or false. ex) flags: [dog, cat, elephant]
#  label_flags: not stable so far. 
#  labels : A class of shape in image is declaed as a list. A shape can have only one class.  ex) labels: [dog, cat, elephant]
##

flags: null
label_flags: null
labels: null
file_search: null
sort_labels: true
validate_label: null

default_shape_color: [0, 255, 0]
shape_color: auto  # null, 'auto', 'manual'
shift_auto_shape_color: 0
label_colors: null

##
#  fill_color:  only 4th element is the alpha; transparency when the mouse hovering on a shape. [transparent 0 <------> 255 opaque]
#  select_fill_color: only 4th element is the alpha; transparency when the shape is selected in edit mode. [transparent 0 <------> 255 opaque]
#  point_size: the point size of all kind of shape. 
##
shape:
  line_color: [0, 255, 0, 128]
  fill_color: [0, 255, 0, 30]  
  vertex_fill_color: [0, 255, 0, 255]
  # selecting / hovering
  select_line_color: [255, 255, 255, 255]
  select_fill_color: [0, 255, 0, 60]
  hvertex_fill_color: [255, 255, 255, 255]
  point_size: 8

# main
flag_dock:
  show: true
  closable: true
  movable: true
  floatable: true
label_dock:
  show: true
  closable: true
  movable: true
  floatable: true
shape_dock:
  show: true
  closable: true
  movable: true
  floatable: true
file_dock:
  show: true
  closable: true
  movable: true
  floatable: true

# label_dialog
show_label_text_field: true
label_completion: startswith
fit_to_content:
  column: true
  row: false

# canvas
epsilon: 10.0
canvas:
  # None: do nothing
  # close: close polygon
  double_click: close
  # The max number of edits we can undo
  num_backups: 10000

shortcuts:
  close: Ctrl+W
  open: Ctrl+O
  open_dir: Ctrl+U
  quit: Ctrl+Q
  save: Ctrl+S
  save_as: Ctrl+Shift+S
  save_to: null
  delete_file: Ctrl+Delete

  open_next: [D, Ctrl+Shift+D]
  open_prev: [A, Ctrl+Shift+A]

  zoom_in: [Ctrl++, Ctrl+=]
  zoom_out: Ctrl+-
  zoom_to_original: Ctrl+0
  fit_window: Ctrl+F
  fit_width: Ctrl+Shift+F

  create_polygon: Ctrl+N
  create_rectangle: Ctrl+R
  create_grid: Ctrl+G
  create_magicbox: Ctrl+T
  create_circle: null
  create_line: null
  create_point: null
  create_linestrip: null
  edit_polygon: Ctrl+J
  delete_polygon: Delete
  duplicate_polygon: Ctrl+D
  copy_polygon: Ctrl+C
  paste_polygon: Ctrl+V
  undo: Ctrl+Z
  undo_last_point: Ctrl+Z
  add_point_to_edge: Ctrl+Shift+P
  edit_label: Ctrl+E
  toggle_keep_prev_mode: Ctrl+P
  remove_selected_point: Backspace
  configure_grid: C

grid: 
  col: 2
  row: 2
  margin : 0 

##
#  epsilon: Defines how tightly the generated polygons represent contour(border of segmented image).
#  iteration: Defines how detailed the grabcut algorithm is to process. The Higher slower, and The lower faster.
#  brush_size: Defines the size of brush in magic box mode
#  convex_hull: If the convex_hull is true, the magic box returns the block hull polygon along with the original convex hull.
##
grabcut: 
  epsilon: 0.001
  iteration: 3
  brush_size: 5
  convex_hull: false

export: 
  export_image_make_sub_dir: false
  export_image_file_prefix: IS
